# Generated by Django 6.0 on 2025-12-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_embeddings_complete',
            field=models.BooleanField(default=False, verbose_name='Векторы получены'),
        ),
    ]
