# Generated by Django 6.0 on 2025-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_document_is_embeddings_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='binary',
        ),
        migrations.AddField(
            model_name='document',
            name='b64',
            field=models.TextField(blank=True, null=True, verbose_name='Файл'),
        ),
    ]
