# Generated by Django 6.0 on 2025-12-28 14:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_document_binary_document_b64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Вектор'),
        ),
    ]
